[user]
name = "Arman Najafian"
email = "n4arman@gmail.com"

[ui]
editor = "nvim"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/github.pub"

[git]
sign-on-push = true
auto-local-bookmark = true
